- name: create user
  ansible.builtin.user:
    name: "{{ user }}"
    state: present
  tags: users
  become: yes

- name: create git cfg
  ansible.builtin.template:
    src: .gitconfig
    dest: "/home/{{ user }}/.gitconfig"
  tags: users
  become: yes

- name: ensures {{ user }}/.ssh dir exists
  file: 
    path: "/home/{{ user }}/.ssh"
    state: directory
  tags: users
  become: yes

- name: load ssh keys
  ansible.builtin.template:
    src: id_rsa.pub
    dest: "/home/{{ user }}/.ssh/id_rsa.pub"
  tags: users
  become: yes

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  become: yes
